export const array_methods = {
  includes: true,
  constructor: true,
  copyWithin: true,
  entries: true,
  every: true,
  indexOf: true,
  join: true,
  keys: true,
  lastIndexOf: true,
  map: true,
  pop: true,
  push: true,
  reduce: true,
  reduceRight: true,
  reverse: true,
  shift: true,
  slice: true,
  some: true,
  sort: true,
  splice: true,
  toLocaleString: true,
  toString: true,
  unshift: true,
  values: true,
}
